### ISSUE TITLE
npm install fails on my system

### ISSUE THREAD

**Issue by code56** [ArianeMora/biojs-vis-box-plot#1]
Running npm install gave me errors, it fails: 
(i got node: v5.0.0, and npm v3.3.7)
npm ERR!     mkdirp build && browserify -r ./:biojs-vis-box-plot -o build/test.js
 
[npm-debug_evanthia_biojs-vis-box-plot.txt](https://github.com/ArianeMora/biojs-vis-box-plot/files/879298/npm-debug_evanthia_biojs-vis-box-plot.txt)

**Comment by code56** [comment]
I have tried it again with 'npm install' and it still fails: 
Failed at the biojs-vis-box-plot@0.1.9 install script 'npm run build'.
npm ERR! This is most likely a problem with the biojs-vis-box-plot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls biojs-vis-box-plot
npm ERR! There is likely additional logging output above.
[npm_evanthia_log.txt](https://github.com/ArianeMora/biojs-vis-box-plot/files/895772/npm_evanthia_log.txt)

**Comment by code56** [comment]
it is giving me this error: 
Error: Cannot find module './box_bar_line.js' from '/Users/kaimakle/Documents/Ph.D./BIOJS/biojs-vis-box-plot/lib'
 
and i checked in the directory indeed I don't have box_bar_line.js, i got index.js, general.js, features.js, axis.js, a.out, ' .

**Comment by ArianeMora** [comment]
I have updated it - please use the html folder and example layout in there (rather than npm install)
